services:
  db:
    image: postgres:15
    container_name: pingme
    environment:
      POSTGRES_DB: pingme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pingme-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env