services:
  db:
    image: postgres:15
    container_name: pingme
    environment:
      POSTGRES_DB: pingme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pingme"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pingme-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
      HTTP_ADDR: ${HTTP_ADDR}
    depends_on:
      db:
        condition: service_healthy

  worker:
    build: .
    container_name: pingme-worker
    command: ["./worker"]
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WORKER_COUNT: ${WORKER_COUNT}
      WORKER_BATCH_SIZE: ${WORKER_BATCH_SIZE}
      WORKER_QUEUE_SIZE: ${WORKER_QUEUE_SIZE}
      SCHEDULER_TICK: ${SCHEDULER_TICK}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      db:
        condition: service_healthy
